### ISSUE TITLE
JDBCドライバのjarファイルのクラスパス追加について

### ISSUE THREAD

**Issue by naokohoriuchi** [naokohoriuchi/Test#1]
tomcat起動時に以下のエラーログが出力されます。
>org.seasar.framework.beans.IllegalPropertyRuntimeException: [ESSR0059]クラス(org.seasar.extension.dbcp.impl.XADataSourceImpl)のプロパティ(driverClassName)の設定に失敗しました。理由はorg.seasar.framework.exception.SIllegalArgumentException: [ESSR0098]クラス(org.seasar.extension.dbcp.impl.XADataSourceImpl)[WebappClassLoader
  context: /sastruts
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@59c9b9ca
]の型(java.lang.String)[null]のプロパティ(driverClassName)に、型(java.lang.String)[null]の値(oracle.jdbc.driver.OracleDriver)を設定できませんでした。対象のクラスは(org.seasar.extension.dbcp.impl.XADataSourceImpl)[WebappClassLoader
  context: /sastruts
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@59c9b9ca
]です。

調べたところ、JDBCドライバのjarファイルのパスをクラスパスに追加すればいいらしいのですが、追加するパスがわからないので教えていただきたいです。

よろしくお願いいたします。

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi 
Tomcatディレクトリの中にlibというディレクトリがありますか？
あれば、そこにjarファイルを入れてTomcatを再起動してみてください。

**Comment by naokohoriuchi** [comment]
どのjarファイルを追加すればよいですか？

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi 
あと、s2jdbc.diconの

<property name="dialect">h2Dialect</property>

の部分ですが、今回はOracle使ってると思うので、

<property name="dialect">oracleDialect</property>

になるかと思います。

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi 
>どのjarファイルを追加すればよいですか？

ojdbc.jarってダウンロードしてない？
してない場合、driverをここからダウンロードしないと。
http://www.oracle.com/technetwork/jp/database/features/jdbc/index-099275-ja.html
バージョンは使ってるOracleのバージョンと同じやつ。

**Comment by naokohoriuchi** [comment]
ojdbc.jarを追加して再起動したら問題なく起動できましたが
データが登録できません（エラーログは出ていません）
sql、serviceなどで何か記述が間違っていますでしょうか？

**Comment by kenichi-nagaoka** [comment]
TransportationService#setTransportaionDataに渡しているパラメータprmTransportationDtoにはちゃんと値はセットされていますか？

**Comment by kenichi-nagaoka** [comment]
あ、
jdbcManager.updateBySqlFile(SET_TRANSPORTATION_DATA, prmTransportationDto)
の後に
.execute();
がない。

こんな形になるはず
jdbcManager.updateBySqlFile(SET_TRANSPORTATION_DATA, prmTransportationDto).execute();

**Comment by naokohoriuchi** [comment]
見落としてました...
失礼しました。

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi 

いったんこのチケットはCloseでOK？
まだ登録できない？

**Comment by naokohoriuchi** [comment]
jdbc.diconのURLの箇所を"jdbc:oracle:thin:@xxx:1521:xxx"のままにしてたので
UnknownHostExceptionが出て登録できないです。。。
このxxxの部分はtnsnames.oraに記載されているホスト名でいいでしょうか？

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi 
そう、tnsnames.oraに書いてあるやつ。多分デフォルトだと以下のようになるかも。

jdbc:oracle:thin:@localhost:1521:XE

**Comment by naokohoriuchi** [comment]
「java.sql.SQLException: not supported」と出ていて登録できません。
調べましたが意味がよくわかりませんでした。
このエラーどういうときに出るものでしょうか？

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi 

PrmTransportationDtoの型がListだからかな？

**Comment by kenichi-nagaoka** [comment]
GetTransportationDtoもそうだけど、PrmTransportationDtoは1レコード1インスタンスで、複数レコード登録、取得したい場合は、そのインスタンスをListにで持つ形になります。
例えば、初期表示でデータを取得するところはこんな形。

`
List<GetTransportationDto> transportationList = transportationService.doGetTransportationData();
`

**Comment by kenichi-nagaoka** [comment]
PrmTransportationDtoはこんな感じになるんじゃ

`
	/** 日付（申請日） */
	public String writeDate;

	/** 部署 */
	public String department;

	/** 名前 */
	public String name;

	/** 日付（乗車日） */
	public String boardingDateList;

	/** 行き先 */
	public String destinationList;

	/** 乗車種別 */
	public String typeList;

	/** 出発地 */
	public String departureList;

	/** 矢印 */
	public String arrowList;

	/** 目的地 */
	public String destinationStationList;

	/** 金額 */
	public String moneyList;

	/** 備考欄 */
	public String remarksList;

	/** 合計金額 */
	public String total;
`

**Comment by naokohoriuchi** [comment]
@kenichi-nagaoka 
FormからパラメータDTOに詰め直す時もList型である必要がありますよね？（Formは申請日、部署、名前、合計金額以外はリストなので）
なので入力された行数文prmTransportationDtoにつめてListに追加し、List型のdspDtoにコピーさせました。
jspで表示させようとしたところ以下のエラーが出ます。
>java.lang.NumberFormatException: For input string: "writeDate"

勝手に数値型に変換しようとしてるのでしょうか？途中のソースは先程コミットしましたので
何か記述間違いなどありましたら教えていただきたいです。

**Comment by kenichi-nagaoka** [comment]
@naokohoriuchi

confirmメソッドの
Beans.copy(prmTransportationDtoList, dspTransportationDto)
ってexecuteっていらない？

**Comment by kenichi-nagaoka** [comment]
NumberFormatExceptionが発生してるのは、confirmメソッドは無事通過して、jsp表示時に発生してますか？（confirmメソッド内で起きてるわけではない？）

**Comment by naokohoriuchi** [comment]
executeつけましたが変わりませんでした。
jsp表示時に発生しています。

**Comment by naokohoriuchi** [comment]
デバックしたらdspTransportationDtoがnullになっていたのでそれが原因かもしれないです。
（Beans.copyが効いてないかもです。）

**Comment by kenichi-nagaoka** [comment]
原因って分かった？
dspTransportationDtoがnullだから？

**Comment by naokohoriuchi** [comment]
dspDtoにコピーするのをやめてprmTransportationDtoListを表示させるようにしました
（"${prmTransportationDtoList[0].writeDate}"と記述したらうまく表示できました。）
が、セッションが保持されていないようで、登録時に空データを登録してしまいます。。。

**Comment by kenichi-nagaoka** [comment]
PrmTransportationDtoの@Componentアノテーションを消してみてください。

**Comment by naokohoriuchi** [comment]
セッション取得できました！

**Comment by kenichi-nagaoka** [comment]
何したら取得できた？

**Comment by naokohoriuchi** [comment]
@componentアノテーションを消したらできました！

**Comment by naokohoriuchi** [comment]
insert文のvalue値がすべて0になってしまうのですが、コメントの直後に値を入れてないからでしょうか？

**Comment by naokohoriuchi** [comment]
値入れてもダメでした＿|￣|○

**Comment by kenichi-nagaoka** [comment]
updateBySqlFileにprmTransportationDtoListを渡してるけど、このリストに格納されてる
PrmTransportationDtoを行数分渡して1件ずつループでインサートしないといけないのでは？

**Comment by naokohoriuchi** [comment]
拡張for文で回したらできました。

**Comment by kenichi-nagaoka** [comment]
これで、登録までできて、あとは一覧の取得とか部署や社員名をDBから取得できるようにできれば一通り完了かな？

**Comment by naokohoriuchi** [comment]
登録までできました。
一覧取得とjsの実装がまだなのでもう少し頑張ります。
遅い時間まで付き合っていただきありがとうございました。

**Comment by kenichi-nagaoka** [comment]
オッケー、そこまで来ればもう少しなので頑張ってみてください！
またわかんないところあれば、今回のようにIssues挙げておいてもらえればと思います。

**Comment by kenichi-nagaoka** [comment]
いったんこのチケットはクローズお願いします。

**Comment by naokohoriuchi** [comment]
![image](https://user-images.githubusercontent.com/39266678/44268766-77cf2800-a26d-11e8-89c1-017827134bcf.png)
